### ISSUE TITLE
import android.support.v4.view.animation.FastOutSlowInInterpolator

### ISSUE THREAD

**Issue by tusharuit25** [cdflynn/checkview#2]
this causes error and library becomes buggy and if added as dependency give R not resolved.

**Comment by cdflynn** [comment]
I was unable to reproduce that error.  I tried importing v1.0 on a few current project workspaces with max target SDK and build tools. 
Still, you can try v1.1 -- all I did there was update the build tools, support library, and target SDK version.

**Comment by tusharuit25** [comment]
Thank  you for your reply it worked...
